version: '3'

services:
  app:
    image: node:14-alpine
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '${APP_DEBUG_PORT}:${APP_DEBUG_PORT}'
    volumes:
      - ./:/srv/app
    command: /bin/sh -c "npm run ${RUN_COMMAND}"
    working_dir: /srv/app
    env_file:
      .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local